name: dart_bump
description: Dart automation tool for safe, consistent version bumps with CHANGELOG generation and Git/OpenAI integration.

version: 1.0.6
repository: https://github.com/gmpassos/dart_bump

executables:
  dart_bump:

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args_simple: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  dependency_validator: ^5.0.3
